[general]
live_config_reload = true

[env]
# TERM = "alacritty"

[terminal.shell]
# program = "/opt/homebrew/bin/bash"
program = "/bin/bash"
args = []                          # ["-norc", "-noprofile"]

[window]
opacity = 0.9
title = "Alacritty Terminal Emulator"


[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

[keyboard]
bindings = [
  # shell commands
  { key = "F6", chars = "$HOME/bin/fzd \n" },

  # todo: create seperate branches for macos / linux / distro
  # all can derived from one common main branch and cherry pick files in as
  # necessary

  # ease of use
  { key = "P", mods = "Command", action = "Paste" },
  { key = "P", mods = "Alt", action = "Paste" },

  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Key0", mods = "Alt", action = "ResetFontSize" },

  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Alt", action = "IncreaseFontSize" },

  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "Minus", mods = "Alt", action = "DecreaseFontSize" },

  { key = "V", mods = "Control", mode = "Vi", action = "ToggleBlockSelection" },
  { key = "Y", mode = "Vi", action = "Copy" },
]

[debug]
render_timer = false
persistent_logging = false
log_level = "warn"
print_events = false
highlight_damage = false
